#!/usr/bin/env python3
"""Generate claude-plugin/ from config/ so the lumi skill library can be
loaded as a personal Claude Code plugin.

`config/` stays the untouched opencode source of truth. This script wipes
and regenerates `claude-plugin/` from it, so it is safe to re-run any time
`config/skills/`, `config/agents/`, `config/opencode.json`, or
`config/AGENTS.md` change. Never hand-edit anything under `claude-plugin/`
— it will be overwritten on the next run.

Run from anywhere:

    python3 script/build_claude_plugin.py
"""

import json
import re
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_SKILLS = REPO_ROOT / "config" / "skills"
SRC_AGENTS = REPO_ROOT / "config" / "agents"
SRC_OPENCODE_JSON = REPO_ROOT / "config" / "opencode.json"
SRC_AGENTS_MD = REPO_ROOT / "config" / "AGENTS.md"
VERSION_FILE = REPO_ROOT / "VERSION"
OUT = REPO_ROOT / "claude-plugin"

# Frontmatter must be the very first thing in the file (Claude Code only
# recognizes a `---` block starting at line 1), so the generated-file notice
# is a YAML comment on the line right after the opening `---`, not a comment
# before it.
GENERATED_COMMENT = (
    "# GENERATED by script/build_claude_plugin.py from config/ — do not "
    "hand-edit; re-run the script instead.\n"
)

# Claude Code `tools:` allowlist per agent, derived from each agent's
# opencode `permission` block (config/agents/*.md). Claude Code has no
# per-bash-command allow/ask/deny granularity, so this collapses each
# opencode permission map to the nearest coarse tool-category allowlist.
AGENT_TOOLS = {
    "tutor": ["Read", "Grep", "Glob", "WebFetch"],
    "analysis": ["Read", "Edit", "Write", "Bash", "Grep", "Glob", "WebFetch"],
    "reviewer-constructive": ["Read", "Grep", "Glob", "WebFetch"],
    "reviewer-critical": ["Read", "Bash", "Grep", "Glob", "WebFetch"],
    "reviewer-physics": ["Read", "Grep", "Glob"],
    "arbiter": ["Read", "Grep", "Glob"],
}

# Agents whose opencode permission block only had a flat allow/ask/deny
# per tool (no interesting sub-command table) don't need a narrowing note.
AGENTS_WITH_SUBCOMMAND_TABLE = {"analysis", "reviewer-critical"}

SUBCOMMAND_NOTE = (
    "\n> **Note (Claude Code adaptation):** the original opencode profile "
    "for this agent allowed specific Bash subcommands automatically (e.g. "
    "`python`, `jupyter`) and required per-command confirmation for others "
    "(`pip`, `curl`, `xrdcp`, …). Claude Code's `Bash` tool does not support "
    "that granularity at the subagent level — rely on Claude Code's own "
    "Bash permission prompts for anything destructive.\n"
)

# Rucio rule-write MCP tools opencode disables today (config/opencode.json
# `tools` block, pattern `rucio-*_rucio_<verb>_rule`). Mirrored here as an
# explicit deny list since `.mcp.json` has no per-tool disable of its own.
RUCIO_SERVERS = ["rucio-atlas", "rucio-cms", "rucio-escape", "rucio-fcc"]
RUCIO_WRITE_VERBS = [
    "add_rule",
    "delete_rule",
    "update_rule",
    "reduce_rule",
    "move_rule",
    "approve_rule",
    "deny_rule",
]

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)

PDF_OLD = """- **PDF text extraction.** opencode's `Read` tool returns binary bytes
  for PDFs and the model cannot interpret them
  ([anomalyco/opencode#9825](https://github.com/anomalyco/opencode/issues/9825)
  — confirmed across Mistral Medium 3, GPT 5.2, Kimi K2.5). **You**
  are responsible for extraction; do not tell the user to run a command
  and paste the result back. Recipe, in order:
  1. `pdftotext '<path>' -` via Bash — read its stdout. Standard on
     lxplus and SWAN.
  2. If `pdftotext` is missing: `python -c "import pypdf; r =
     pypdf.PdfReader('<path>'); print('\\n\\n'.join(p.extract_text()
     for p in r.pages))"` (or `pdfplumber` if available).
  3. If both fail, report the actual error before suggesting any
     user-side workaround.
  Remove this guideline once #9825 is resolved in the opencode binary
  lumi ships."""

PDF_NEW = """- **PDF text extraction.** Claude Code's `Read` tool extracts PDF text
  natively — pass `pages` for documents over 10 pages. Use it directly
  instead of shelling out to `pdftotext` or `pypdf`."""


def extract_field(frontmatter: str, field: str) -> str:
    """Line-oriented extraction, matching config/evals/lint.py's approach:
    descriptions contain ': ' (e.g. 'Disambiguator phrase: ...'), which is
    illegal in unquoted YAML scalars, so this reads the raw line instead of
    parsing YAML."""
    for line in frontmatter.splitlines():
        if line.startswith(f"{field}:"):
            return line[len(field) + 1 :].strip()
    raise ValueError(f"missing {field!r} field")


def build_skills():
    # Claude Code only discovers skills one level deep as
    # skills/<name>/SKILL.md — it does not walk category subfolders
    # (config/skills/access/rucio/SKILL.md, etc., confirmed by probing the
    # CLI directly). config/AGENTS.md already documents that skills are
    # resolved by `name:` frontmatter, not by path, and every skill dir's
    # basename already matches its `name:` — so flattening one level is
    # safe and loses no information.
    dest = OUT / "skills"
    dest.mkdir(parents=True)
    seen = {}
    for skill_md in sorted(SRC_SKILLS.rglob("SKILL.md")):
        skill_dir = skill_md.parent
        name = skill_dir.name
        if name in seen:
            raise ValueError(
                f"skill name collision when flattening: {skill_dir} and "
                f"{seen[name]} both produce skills/{name}/"
            )
        seen[name] = skill_dir
        shutil.copytree(skill_dir, dest / name)
    return len(seen)


def build_agents():
    dest = OUT / "agents"
    dest.mkdir(parents=True)
    count = 0
    for src in sorted(SRC_AGENTS.glob("*.md")):
        name = src.stem
        text = src.read_text()
        match = FRONTMATTER_RE.match(text)
        if not match:
            raise ValueError(f"{src}: no YAML frontmatter block found")
        frontmatter, body = match.groups()
        description = extract_field(frontmatter, "description")
        tools = AGENT_TOOLS.get(name)
        if tools is None:
            raise ValueError(
                f"{src}: no AGENT_TOOLS mapping for {name!r} — add one "
                "before regenerating"
            )

        new_frontmatter = (
            "---\n"
            + GENERATED_COMMENT
            + f"name: {name}\n"
            f"description: {description}\n"
            f"tools: {', '.join(tools)}\n"
            "---\n"
        )
        new_body = body
        if name in AGENTS_WITH_SUBCOMMAND_TABLE:
            new_body = new_body.rstrip("\n") + "\n" + SUBCOMMAND_NOTE

        (dest / f"{name}.md").write_text(new_frontmatter + new_body)
        count += 1
    return count


def build_mcp_json():
    config = json.loads(SRC_OPENCODE_JSON.read_text())
    mcp = config["mcp"]
    servers = {}
    for server_name, server_cfg in mcp.items():
        # Drop opencode-only fields (oauth.clientId is a CIMD document
        # scoped to opencode's own redirect URI; Claude Code performs its
        # own OAuth handshake and needs no client-id override here).
        servers[server_name] = {"type": "http", "url": server_cfg["url"]}

    (OUT / ".mcp.json").write_text(
        json.dumps({"mcpServers": servers}, indent=2) + "\n"
    )
    return len(servers)


def build_settings_json():
    deny = [
        f"mcp__{server}__rucio_{verb}"
        for server in RUCIO_SERVERS
        for verb in RUCIO_WRITE_VERBS
    ]
    settings = {"permissions": {"deny": deny}}
    (OUT / "settings.json").write_text(json.dumps(settings, indent=2) + "\n")
    return len(deny)


def build_plugin_json():
    version = VERSION_FILE.read_text().strip()
    manifest = {
        "name": "lumi",
        "description": (
            "General CERN assistant — open data, service operations "
            "(Rucio, FTS, REANA, EOS, SWAN, HTCondor, CRIC), and physics "
            "analysis skills, agents, and MCP tools."
        ),
        "version": version,
        "author": {
            "name": "Giovanni Guerrieri",
            "email": "giovanni.guerrieri@cern.ch",
        },
    }
    plugin_dir = OUT / ".claude-plugin"
    plugin_dir.mkdir(parents=True)
    (plugin_dir / "plugin.json").write_text(json.dumps(manifest, indent=2) + "\n")


def build_lumi_command():
    text = SRC_AGENTS_MD.read_text()
    if PDF_OLD not in text:
        raise ValueError(
            "AGENTS.md's PDF-extraction guideline text has changed — update "
            "PDF_OLD/PDF_NEW in this script to match before regenerating"
        )
    text = text.replace(PDF_OLD, PDF_NEW)

    dest = OUT / "commands"
    dest.mkdir(parents=True)
    frontmatter = (
        "---\n"
        + GENERATED_COMMENT
        + "description: Load the Lumi CERN-assistant persona, critical "
        "rules, and skill routing guide for this session\n"
        "---\n\n"
    )
    (dest / "lumi.md").write_text(frontmatter + text)


def build_readme():
    version = VERSION_FILE.read_text().strip()
    (OUT / "README.md").write_text(
        f"""# lumi (Claude Code plugin)

{GENERATED_COMMENT.replace("# ", "").strip()}
Source of truth: `config/skills/`, `config/agents/`, `config/opencode.json`,
`config/AGENTS.md` in this repo. To pick up a change, run
`python3 script/build_claude_plugin.py` from the repo root and reload.

Generated from lumi-assistant v{version}.

## Try it for one session

```
claude --plugin-dir {OUT}
```

## Install it permanently (personal, this machine only)

```
ln -s {OUT} ~/.claude/skills/lumi
```

It auto-loads on the next Claude Code session as `lumi@skills-dir`. Run
`/reload-plugins` inside an already-running session to pick it up without
restarting. To remove it: `claude plugin disable lumi@skills-dir` (or
delete the symlink).

## What's in here

- `skills/` — the 27 lumi skills, flattened one level (Claude Code only
  discovers `skills/<name>/SKILL.md`, not category subfolders — see the
  build script for why).
- `agents/` — the 6 lumi subagents (`tutor`, `analysis`, `reviewer-physics`,
  `reviewer-critical`, `reviewer-constructive`, `arbiter`), with `tools:`
  allowlists approximating the original opencode permission profiles.
- `commands/lumi.md` — `/lumi`, loads the Lumi persona, critical rules,
  and skill routing guide into the session (adapted from
  `config/AGENTS.md`).
- `.mcp.json` — the 7 remote MCP servers (`atlasopenmagic`, `cernopendata`,
  `cerndocs`, and the 4 per-VO `rucio-*` servers). Rucio OAuth runs through
  Claude Code's own remote-MCP OAuth flow, not opencode's CIMD bridge.
- `settings.json` — denies the Rucio rule-write MCP tools, mirroring the
  disable list in `config/opencode.json`.

## Known gaps vs. the opencode config

- Fine-grained per-Bash-subcommand policy (opencode's `ask`/`allow`/`deny`
  per command) has no Claude Code subagent equivalent — agents get a
  coarser `tools:` allowlist instead; see the note inside `agents/analysis.md`
  and `agents/reviewer-critical.md`.
- The multi-provider model/gateway config in `config/opencode.json`
  (LiteLLM, aigw, non-Anthropic models) does not port — this plugin runs
  on whatever model the host Claude Code session is using.
- The Rucio MCP servers' OAuth flow has not yet been exercised end-to-end
  through Claude Code's native flow (only through opencode's CIMD bridge).
  Verify on first real use.
"""
    )


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()

    n_skills = build_skills()
    n_agents = build_agents()
    n_mcp = build_mcp_json()
    n_deny = build_settings_json()
    build_plugin_json()
    build_lumi_command()
    build_readme()

    print(f"claude-plugin/ generated at {OUT}")
    print(f"  skills:   {n_skills}")
    print(f"  agents:   {n_agents}")
    print(f"  mcp:      {n_mcp}")
    print(f"  denied:   {n_deny} rucio rule-write tool names")


if __name__ == "__main__":
    main()
