#!/usr/bin/env python3
"""Sync vendored skills from upstream skill repositories.

Why vendor-with-override (not submodule / subtree): lumi MUST rewrite
each skill's `description:` to anchor it to the CERN domain and assign
`data_scope` + `experiment` (cliff prevention — generic descriptions
out-route lumi's domain skills). Submodules and subtrees break when the
tracked content is modified. Vendoring with a per-skill frontmatter
override gives full control of the routing-relevant fields while pulling
the body unchanged from upstream.

Layout:
  script/vendor/
    sources.yaml              <- upstream repos + the vendored skill list
    <skill>.frontmatter.md    <- lumi's frontmatter override (one per skill)

Output:
  config/skills/<bucket>/<skill>/SKILL.md

Usage (from repo root):
  python script/sync_vendored.py           # rebuild every vendored skill
  python script/sync_vendored.py --check   # dry-run; report drift, exit 2
"""
from __future__ import annotations

import sys
from pathlib import Path

import httpx
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCES = REPO_ROOT / "script" / "vendor" / "sources.yaml"
VENDOR_DIR = REPO_ROOT / "script" / "vendor"
SKILLS_ROOT = REPO_ROOT / "config" / "skills"


def raw_url(repo: str, sha: str, rel_path: str) -> str:
    """Translate https://github.com/<org>/<name> -> raw URL for a path."""
    base = repo.replace("github.com", "raw.githubusercontent.com").rstrip("/")
    return f"{base}/{sha}/{rel_path}"


def strip_frontmatter(text: str) -> str:
    """Drop a leading YAML frontmatter block; return the body verbatim.

    Strips only the first --- ... --- block. Any --- horizontal rules in
    the body are preserved.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return text.strip("\n")
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[i + 1:]).strip("\n")
    return text.strip("\n")


def main() -> int:
    check_only = "--check" in sys.argv[1:]

    if not SOURCES.exists():
        print(f"error: missing {SOURCES}", file=sys.stderr)
        return 1

    spec = yaml.safe_load(SOURCES.read_text())
    sources = spec.get("sources", {})
    vendored = spec.get("vendored", [])
    if not vendored:
        print("error: sources.yaml has no `vendored:` entries", file=sys.stderr)
        return 1

    drift = False
    for entry in vendored:
        skill = entry["skill"]
        bucket = entry["bucket"]
        src = sources[entry["source"]]

        rel_path = src["path"].format(skill=skill, plugin=entry.get("plugin", ""))
        url = raw_url(src["repo"], src["sha"], rel_path)
        override_path = VENDOR_DIR / f"{skill}.frontmatter.md"
        out_path = SKILLS_ROOT / bucket / skill / "SKILL.md"

        print(f"\n  {skill}")
        print(f"    source:   {entry['source']} @ {src['sha'][:12]}")
        print(f"    upstream: {url}")
        print(f"    output:   {out_path.relative_to(REPO_ROOT)}")

        if not override_path.exists():
            print(f"    error: missing override {override_path}", file=sys.stderr)
            return 1

        try:
            resp = httpx.get(url, follow_redirects=True, timeout=30)
            resp.raise_for_status()
        except httpx.HTTPError as exc:
            print(f"    error: fetch failed: {exc}", file=sys.stderr)
            return 1

        body = strip_frontmatter(resp.text)
        if not body:
            print("    error: upstream body empty after stripping frontmatter",
                  file=sys.stderr)
            return 1

        header = (
            f"<!-- Vendored from {src['repo']} @ {src['sha']} on {src['date']}.\n"
            f"     Do not edit this file directly; modify\n"
            f"     script/vendor/{skill}.frontmatter.md and re-run\n"
            f"     python script/sync_vendored.py. -->"
        )
        override = override_path.read_text().rstrip("\n")
        new_content = f"{override}\n{header}\n{body}\n"

        if check_only:
            current = out_path.read_text() if out_path.exists() else ""
            if current != new_content:
                print(f"    DRIFT: would change {out_path.relative_to(REPO_ROOT)}")
                drift = True
            else:
                print("    ok")
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(new_content)
            print("    written")

    if check_only and drift:
        print("\nDrift detected. Re-run without --check to update.")
        return 2
    if check_only:
        print("\nNo drift.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
